version: '3'

services:
  mongo:
    image: mongo
  wgc:
    image: ivolchenkov/wgc
    ports:
      - 51820:51820/udp
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
  wgb:
    image: ivolchenkov/wgb
    depends_on:
      - wgc
      - mongo
    environment:
      - APP_endpoint=192.168.3.8