version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=wednesday
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wednesday_vpn
  wgc:
    image: ivolchenkov/wgc
    ports:
      - 51820:51820/udp
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
  wgb:
    image: ivolchenkov/wgb
    depends_on:
      - wgc
      - postgres
    environment:
      - APP_endpoint=192.168.3.8